// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pjwmfyvknbtoofxfuwjm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBqd21meXZrbmJ0b29meGZ1d2ptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3OTQ2NTgsImV4cCI6MjA2MDM3MDY1OH0.yrje_gdq9gODnMZbxUO6giRz4ID4SOpcmBlBOIDOK1U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Konfigurasi persisten sesi untuk menyimpan login dalam waktu lama
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true, // Aktifkan penyimpanan sesi persisten
    storageKey: 'finance_friend_auth', // Kunci penyimpanan untuk localStorage
    autoRefreshToken: true, // Secara otomatis refresh token
    detectSessionInUrl: true, // Deteksi sesi dalam URL (untuk OAuth)
    storage: localStorage // Gunakan localStorage untuk menyimpan sesi
  }
});